# /charts/spring-petclinic-service/chart/values.yaml
replicas: 2

image:
  repository: 22127210/spring-petclinic-config-server
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

env: []


livenessProbe:
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
