
image:
  repository: 22127210/spring-petclinic-api-gateway
  tag: "74b53db"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8080
  type: ClusterIP

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: CONFIG_SERVER_URL
    value: http://config-server.petclinic-core.svc.cluster.local:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server.petclinic-core.svc.cluster.local:8761/eureka
