apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: checkout-dev-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # Git generator scanning all subdirectories under environment/checkout-dev/
          - git:
              repoURL: 'https://github.com/wasdqaz/spring-petclinic-microservices-config.git'
              revision: HEAD
              directories:
                - path: 'environment/checkout-dev/*'
          # List of microservice names
          - list:
              elements:
                - name: vets-service
                - name: visits-service
                - name: customers-service
                - name: api-gateway
                - name: admin-server
                - name: config-server
                - name: discovery-server
                - name: genai-service
  template:
    metadata:
      # Application name composed of directory basename and service name
      name: '{{path.basename}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/wasdqaz/spring-petclinic-microservices-config.git'
        targetRevision: HEAD
        path: 'charts/spring-petclinic-chart'
        helm:
          releaseName: '{{name}}'
          valueFiles:
            # Values file path relative to the repo root, matching your directory structure
            - ../../values/checkout-dev/{{path.basename}}/values-{{name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        # Namespace named after the directory basename to isolate environments
        namespace: 'checkout-dev-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
