# environment/checkout_dev/environmentet.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: checkout-dev-environment
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/wasdqaz/spring-petclinic-microservices-config.git'
              revision: HEAD
              directories:
                - path: 'environment/checkout_dev/checkout_dev-*'
          - list:
              elements:
                - name: vets-service
                - name: visits-service
                - name: customers-service
                - name: api-gateway
                - name: admin-server
                - name: config-server
                - name: discovery-server
                - name: genai-service
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/wasdqaz/spring-petclinic-microservices-config.git'
        targetRevision: HEAD
        path: 'charts/spring-petclinic-chart'
        helm:
          valueFiles:
            - ../../values/checkout_dev/{{path.basename}}/values-{{name}}.yaml
          releaseName: '{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'checkout-dev-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
