
image:
  repository: 22127210/null
  tag: "null"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 9090
  type: ClusterIP
  name: null


env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: CONFIG_SERVER_URL
    value: http://config-server.petclinic-core.svc.cluster.local:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server.petclinic-core.svc.cluster.local:8761/eureka
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  path: /actuator/health
  port: null
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  port: null
  initialDelaySeconds: 60
  periodSeconds: 15

