
image:
  repository: 22127210/spring-petclinic-admin-server
  tag: "latest"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 9090
  type: ClusterIP
  name: spring-petclinic-admin-server

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka
  - name: EUREKA_INSTANCE_HOSTNAME
    value: admin-server 

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  path: /actuator/health
  port: 9090
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  port: 9090
  initialDelaySeconds: 60
  periodSeconds: 15
