# dev/values-genai-service.yaml
image:
  repository: 22127210/spring-petclinic-genai-service
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8084
  type: ClusterIP
  name: genai-service

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka
  - name: EUREKA_INSTANCE_HOSTNAME
    value: genai-service


resources:
  limits:
    cpu: "1"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

readinessProbe:
  path: /actuator/health
  port: 8084
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  port: 8084
  initialDelaySeconds: 60
  periodSeconds: 15