# dev/values-vets-service.yaml
image:
  repository: 22127210/spring-petclinic-vets-service
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8083
  type: ClusterIP
  name: vets-service

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka
  - name: EUREKA_INSTANCE_HOSTNAME
    value: vets-service

    
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  path: /actuator/health
  port: 8083
  initialDelaySeconds: 20
  periodSeconds: 5

livenessProbe:
  path: /actuator/health
  port: 8083
  initialDelaySeconds: 40
  periodSeconds: 10