# apps/staging/vets-service.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vets-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/hzeroxium/spring-petclinic-microservices-config
    path: charts/spring-petclinic-service
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/staging/values-vets-service.yaml
      releaseName: vets-service
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
