apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/wasdqaz/spring-petclinic-microservices-config
    path: charts/spring-petclinic-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/dev/values-api-gateway.yaml
      releaseName: api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
