# apps/dev/discovery-server.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery-server-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/hzeroxium/spring-petclinic-microservices-config
    path: charts/spring-petclinic-service
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/dev/values-discovery-server.yaml
      releaseName: discovery-server
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
