# apps/base/admin-server.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hzeroxium/spring-petclinic-microservices-config
    path: charts/spring-petclinic-service
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../dev/values-admin-server.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
