
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-genai-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: checkout-dev
spec:
  project: default
  source:
    repoURL: https://github.com/wasdqaz/spring-petclinic-microservices-config.git
    path: charts/spring-petclinic-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/checkout-dev/fixCICD2/values-spring-petclinic-genai-service.yaml
      releaseName: genai-service
  destination:
    server: https://kubernetes.default.svc
    namespace: checkout-dev-fixCICD2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
